### ISSUE TITLE
Joke Issue Template

### ISSUE THREAD

**Issue by StartAutomating** [PowerShellWeb/PSJekyll#131]
### Set Up

I give you a [Joke issue template](https://github.com/PowerShellWeb/PSJekyll/issues/new?assignees=&labels=joke&projects=&template=Joke.yml):

```yaml
name: Joke
description: Share a Joke
labels: ["joke"]
body:
  - type: markdown
    attributes:
      value: |
        Please be funny.
  - type: textarea
    id: Setup
    attributes:
      label: Set Up      
    validations:
      required: true
  - type: textarea
    id: Punchline 
    attributes:
      label: Punchline
    validations:
      required: true  
```

### Punchline

Have pun!
